---
- name: Install dev packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - htop
      - neofetch
      - most
      - screen
      - tmux
      - nano
      - vim
      - nano-syntax-highlighting
      - neovim
      - mc
      - ncdu
      - wget
      - curl
      - bind-tools
      - rsync
      - unzip
      - p7zip
    state: present

- name: Install neovim-plug
  kewlfft.aur.aur:
    use: yay
    name:
      - neovim-plug
    extra_args: --nocleanmenu --nodiffmenu

- name: Install libffi6
  kewlfft.aur.aur:
    use: yay
    name:
      - libffi6
