- hosts: archs:manjaros
  gather_facts: yes
  pre_tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 600
    tags:
      - preinstall

  - name: Detect if cloud-init generated
    stat:
      path: /etc/cloud/cloud.cfg
    register: cloud_init_cfg
    tags:
      - preinstall

  - name: Wait for cloud-init / user-data to finish
    command: cloud-init status --wait
    changed_when: no
    when: cloud_init_cfg.stat.exists
    tags:
      - preinstall

  - name: Edit sudoers
    become: yes
    community.general.sudoers:
      name: 99-wheel-nopasswd
      group: wheel
      commands: ALL
      nopassword: true
      state: present
      validation: required
    tags:
      - preinstall

  - name: Remove snap
    include_role:
      name: bodsch.snapd

  - name: Gather the package facts
    package_facts:
      manager: auto

  roles:
  - update-all-via-pacman-or-yay
  - enable-aurs
  - install-dev-packages
  - role: install-nodejs
    when: "'nodejs' in components_to_install"
  - role: install-jdk8-maven
    when: "'jdk8-maven' in components_to_install"
  - role: install-jdk11
    when: "'jdk11' in components_to_install"
  - role: install-zsh
    when: "'zsh' in components_to_install"
  - role: install-aws
    when: "'aws' in components_to_install"
  - install-setup-git
  - role: install-micromamba
    when: "'micromamba' in components_to_install"
  - role: install-docker
    when: "'docker' in components_to_install"
  - role: install-docker-compose
    when: "'docker-compose' in components_to_install"
  - role: install-rust-utils
    when: "'rust' in components_to_install"
  - update-all-via-pacman-or-yay
  - role: install-server-extras
    when: "'server-extras' in components_to_install"
  - role: install-julia
    when: "'julia' in components_to_install"
