- name: Create/update user {{ user }}
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ zsh_path }}"
    state: present

- name: Add user to secondary groups for user {{ user }}
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ group_name }}"
    append: true
  when: group_name in ansible_facts.getent_group
  loop:
    - docker
    - libvirt
  loop_control:
    loop_var: group_name
