---
- name: Perform user actions for users
  hosts: archs:manjaros
  gather_facts: false
  tasks:
    - name: Perform user actions for user
      ansible.builtin.include_role:
        name: install_server_stuff_user
      loop: "{{ users }}"
      loop_control:
        loop_var: user
