---
- name: Perform sysadmin actions for users
  hosts: archs:manjaros
  gather_facts: false
  tasks:
    - name: Get zsh path
      ansible.builtin.command: which zsh
      register: zsh_path_result
      changed_when: false

    - name: Get all groups
      ansible.builtin.getent:
        database: group
        split: ":"

    - name: Perform sysadmin actions for user
      ansible.builtin.include_role:
        name: sysadmin_user
      vars:
        zsh_path: "{{ zsh_path_result.stdout }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user
