---
- name: Install pacman mirrors
  become: yes
  pacman:
    name: pacman-mirrors
  when: ansible_facts['kernel'] is search("MANJARO")

- name: Set pacman mirrors
  become: yes
  command: pacman-mirrors --country {{ pacman_mirrors_country }}
  when: ansible_facts['kernel'] is search("MANJARO")

- name: Update via yay if yay is installed
  become: no
  kewlfft.aur.aur:
    use: yay
    upgrade: yes
    update_cache: yes
    aur_only: no
  when: "'yay' in ansible_facts.packages"
  notify:
  - Reboot after update

- name: Otherwise update via pacman
  become: yes
  pacman:
    update_cache: yes
    upgrade: 'yes'
  when: "'yay' not in ansible_facts.packages"
  notify:
  - Reboot after update

- name: Flush handlers
  meta: flush_handlers
