- hosts: ubuntus
  become: yes
  gather_facts: yes # required by bodsch.snapd
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 600

  - name: Wait for cloud-init / user-data to finish
    command: cloud-init status --wait
    changed_when: no

  - name: Install qemu guest agent
    apt:
      update_cache: yes
      name: qemu-guest-agent
      state: present

  - name: Make sure qemu guest agent is running
    systemd:
      name: qemu-guest-agent
      enabled: yes
      state: started

  - name: Remove Snap
    include_role:
      name: bodsch.snapd

  - name: Copy over the timesyncd config
    copy:
      src: ../templates/timesync.conf
      dest: /etc/systemd/timesyncd.conf
    register: timesyncd_config

  - name: Make sure timesyncd is restarted
    systemd:
      name: systemd-timesyncd.service
      state: restarted
    when: timesyncd_config.changed
