---
- name: Configure parallel downloads for pacman
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    search_string: 'ParallelDownloads'
    line: ParallelDownloads = {{ pacman_parallel_downloads }}
    state: present

- name: Install pacman mirrors
  become: true
  community.general.pacman:
    name: pacman-mirrors
  when: is_manjaro

- name: Set pacman mirrors
  become: true
  ansible.builtin.command: pacman-mirrors --country {{ pacman_mirrors_country }}
  when: is_manjaro
  changed_when: true
  notify:
    - Reboot after update

- name: Update via yay if yay is installed
  become: false
  kewlfft.aur.aur:
    use: yay
    upgrade: true
    update_cache: true
    aur_only: false
  when: is_yay
  notify:
    - Reboot after update
  register: update_result_yay

- name: Otherwise update via pacman
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: 'yes'
  when: not is_yay
  notify:
    - Reboot after update
  register: update_result_pacman

- name: Debug update_result
  debug:
    var: update_result
    verbosity: 2

- name: Prompt for reboot
  ansible.builtin.pause:
    prompt: "Machine requires reboot after update, proceed?(y/n)"
    echo: true
  register: reboot_confirmation
  when: ansible_connection=="local" and ((update_result_yay is defined and update_result_yay.changed) or (update_result_pacman is defined and update_result_pacman.changed))

- name: Debug reboot confirmation
  debug:
    var: reboot_confirmation
    verbosity: 2

- name: Manual reboot after update
  become: true
  ansible.builtin.command: reboot now
  when: ansible_connection=="local" and reboot_confirmation is defined and reboot_confirmation.user_input is defined and reboot_confirmation.user_input=="y"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
