---
- name: Change hostname
  hosts: "*"
  become: yes
  gather_facts: no
  tasks:

  - name: Register file
    stat:
      path: /etc/cloud/cloud.cfg
    register: register_name

  - name: Check if the file exists
    debug:
      msg: "The file or directory exists"
    when: register_name.stat.exists

  - name: Turn off Preserve hostname on Ubuntu
    replace:
      path: /etc/cloud/cloud.cfg
      regexp: '(^preserve_hostname:\s)(.*)$'
      replace: '\1false'
    when: register_name.stat.exists

  - name: "update hostnames"
    hostname:
      name: "{{ new_hostname }}"
