---
- name: Install Stack Haskell platform (dependency for ERD)
  kewlfft.aur.aur:
    use: yay
    name:
      - stack

- name: Install FAR for Linux
  kewlfft.aur.aur:
    use: yay
    name:
      - far2l-git
    extra_args: --nocleanmenu --nodiffmenu -vvv
