---
- name: Check whether broot is installed
  ansible.builtin.command: which broot &>/dev/null
  register: broot_exists
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Install or reinstall the br shell function
  ansible.builtin.command: broot --install
  when: broot_exists.rc == 0
  changed_when: true

- name: Config diff so fancy paget in git
  community.general.git_config:
    name: core.pager
    scope: global
    value: "diff-so-fancy | less --tabs=4 -RFX"

- name: Create .zprofile if it doesn't exist
  ansible.builtin.file:
    path: $HOME/.zprofile
    mode: '0644'
    state: touch

- name: Check if binary is exported, if no add this config to .zprofile
  ansible.builtin.lineinfile:
    path: $HOME/.zprofile
    search_string: 'export PATH="$HOME/.cargo/bin:$PATH"'
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present
