- name: install latest qemu-guest-agent
  hosts: "*"
  gather_facts: yes
  debugger: always
  tasks:
    - name: print all available facts
      debug:
        var: ansible_facts['os_family']
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
      become: yes
      when: ansible_facts['os_family'] == "Debian"
