---
- name: Install nodejs, yarn, npm
  become: yes
  pacman:
    name:
      - nodejs
      - yarn
      - npm
    state: present

- name: Install less
  become: yes
  npm:
    name: less
    global: yes