---
- name: Install yay via pacman
  become: yes
  pacman:
    name: yay
    state: present
  when: is_manjaro and (not is_yay)

- name: Build yay for Arch from binaries
  when: (not is_manjaro) and (not is_yay)
  block:
    - name: Remove directories before building yay from binaries
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - ./yay-bin
        - ./yay

    - name: Clone yay-bin
      become: no
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: ./yay-bin
 
    - name: Build yay from binaries
      become: no
      command:
        cmd: makepkg -si --noconfirm
        chdir: ./yay-bin

    - name: Remove directories after building yay from binaries
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - ./yay-bin
        - ./yay

- name: Configure pamac for Manjaro
  when: is_manjaro
  block:
    - name: Install pamac-cli
      become: no
      kewlfft.aur.aur:
        use: yay
        name: pamac-cli

    - name: Enable AUR in pamac
      become: yes
      replace:
        path: /etc/pamac.conf
        regexp: '#EnableAUR'
        replace: 'EnableAUR'

- name: Install pigz and pbzip2
  kewlfft.aur.aur:
    use: yay
    name:
      - pigz
      - pbzip2
