---
- debug:
    msg: Processing user {{ user }}
  changed_when: no

- include_role:
    name: "{{ role }}"
    apply:
      become_user: "{{ user }}"
  loop:
    - config-jupyter
    - install-ohmyzsh
    - config-diff-so-fancy
    - config-git
    - config-tig
  loop_control:
    loop_var: role
