---
- name: Install git, git-lfs, tig
  become: yes
  pacman:
    name:
      - git
      - git-lfs
      - tig
    state: present

- name: Configure git
  command: git config --global core.fileMode true
