---
- name: Install git, git-lfs, tig
  become: yes
  pacman:
    name:
      - git
      - git-lfs
      - tig
    state: present

- name: Configure git
  git_config:
    name: core.fileMode
    scope: global
    value: "true"
