all:
  children:
    suser_group:
      hosts:
        10.3.1.21:
        10.3.1.31:
    suser2_group:
      hosts:
        10.3.1.22:
        10.3.1.23:
        10.3.1.32:
    ubuntus:
      hosts: 10.3.1.[21:23]
    archs:
      hosts: 10.3.1.[31:32]
    manjaros:
      hosts: 10.3.1.41
