---
- name: Install docker
  become: yes
  pacman:
    name:
      - docker
    state: present

- name: Configure docker
  become: yes
  command: 'systemctl enable docker --now; usermod -aG docker $USER;'

#TO DO