---
- name: Install docker
  become: yes
  pacman:
    name:
      - docker
    state: present

- name: Enable & start docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  become: yes
  command: usermod -aG docker {{ ansible_user }}

- name: Create docker config
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
  - Restart docker after adding/changing daemon.json
