---
- name: Set fileMode for git
  community.general.git_config:
    name: core.fileMode
    scope: global
    value: "true"

- name: Set editor for git
  community.general.git_config:
    name: core.editor
    scope: global
    value: "nvim"
