  GNU nano 6.2                                                                                        ./playbooks/install_4server_all3.yml                                                                                                  
- hosts: manjaros
  gather_facts: yes
  tasks:
  - name: Edit sudoers
    become: yes
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '^%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Remove snap
    include_role:
      name: bodsch.snapd

  - name: Gather the package facts
    package_facts:
      manager: auto

  - name: Update via yay if yay is installed
    command: "yay -Syyuu --nocleanmenu --nodiffmenu --noconfirm --needed"
    when: "'yay' in ansible_facts.packages"

  - name: Otherwise update via pacman
    become: yes
    command: "pacman -Syyuu --noconfirm --needed"
    when: "'yay' not in ansible_facts.packages"
