---
- name: Check whether broot is installed
  command: which broot &>/dev/null
  register: broot_exists
  ignore_errors: yes
  failed_when: no

- name: Install or reinstall the br shell function
  command: broot --install
  when: broot_exists.rc == 0

- name: Config diff so fancy paget in git
  git_config:
    name: core.pager
    scope: global
    value: "diff-so-fancy | less --tabs=4 -RFX"

- name: Check if binary is exported, if no add this config to .zprofile
  lineinfile:
    path: $HOME/.zprofile
    search_string: 'export PATH="$HOME/.cargo/bin:$PATH"'
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present

- name: Update .zshrc
  shell: . $HOME/.zshrc
  ignore_errors: yes
  failed_when: no

- name: Update .zprofile
  shell: . $HOME/.zprofile
  