---
- name: Copy config folder
  ansible.builtin.copy:
    src: .jupyter
    dest: $HOME/
    mode: '0644'

- name: Make copies of files within config folder
  ansible.builtin.copy:
    remote_src: true
    src: $HOME/.jupyter/jupyter_notebook_config.{{ extension }}
    dest: $HOME/.jupyter/jupyter_lab_config.{{ extension }}
    mode: '0644'
  loop:
    - py
    - json
  loop_control:
    loop_var: extension
